-- AlterTable
ALTER TABLE "DailyIntake" ADD COLUMN     "totalFat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalProtein" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSugar" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Meal" ADD COLUMN     "fat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "protein" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sugar" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "UserMeal" ADD COLUMN     "totalFat" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalProtein" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalSugar" DOUBLE PRECISION NOT NULL DEFAULT 0;
